name: On Branch Push

on:
  push:
    branches:
      - main

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.5'

      - name: Get dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install gcc \
          libgl1-mesa-dev libegl1-mesa-dev \
          libgles2-mesa-dev libx11-dev xorg-dev \
          libwayland-dev libxkbcommon-dev bc
