name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            targets: ["linux", "windows"]
          - os: macos-latest
            targets: ["darwin"]

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest

      - name: Pull latest Docker images
        if: matrix.platform.os == 'ubuntu-latest'
        run: fyne-cross --pull

      - name: Build for each target
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          for target in ${{ join(matrix.platform.targets, ' ') }}; do
            fyne-cross $target -arch=* -output app -app-version $VERSION -app-id com.example.app
          done

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.os }}-builds
          path: dist/*
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*-builds'
          path: dist

      - name: Flatten artifacts
        run: |
          mkdir -p release-assets
          find dist -type f -exec mv {} release-assets/ \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-assets/*